[project]
authors = ["Shlok Natarajan <shlok.natarajan@gmail.com>"]
channels = ["conda-forge"]
name = "encoder-testing"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
transformers = ">=4.50.0,<5"
pytorch = ">=2.6.0,<3"
python-dotenv = ">=1.1.0,<2"
ipykernel = ">=6.29.5,<7"
datasets = ">=3.4.1,<4"
loguru = ">=0.7.2,<0.8"
scikit-learn = ">=1.6.1,<2"
matplotlib = ">=3.10.1,<4"
pydantic = ">=2.11.2,<3"
